name: Docker Image CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . \
        --file ./gw-build/Dockerfile \
        --build-arg IGNITION_VERSION=8.1.26 \
        --tag ignition_test:$(date +%s)
